### ISSUE TITLE
LogException using Pulumi.Automation in C#

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi-dotnet#163]
### What happened?

```
Pulumi.LogException: Error occurred during logging

Pulumi.LogException
Error occurred during logging
   at Pulumi.Deployment.EngineLogger.LogAsync(LogSeverity severity, String message, Resource resource, Nullable`1 streamId, Nullable`1 ephemeral)
   at Pulumi.Deployment.Runner.LogExceptionToErrorStream(Exception exception)
   at Pulumi.Deployment.Runner.HandleExceptionsAsync(IEnumerable`1 exceptions)
   at Pulumi.Deployment.<>c__DisplayClass71_0.<<RunInlineAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Pulumi.Automation.WorkspaceStack.UpAsync(UpOptions options, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.UpAsync(UpOptions options, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)

Grpc.Core.RpcException
Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: Connection refused (127.0.0.1:52034) SocketException: Connection refused", DebugException="System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:52034)
 ---> System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Pulumi.GrpcEngine.LogAsync(LogRequest request)
   at Pulumi.Deployment.EngineLogger.LogAsync(LogSeverity severity, String message, Resource resource, Nullable`1 streamId, Nullable`1 ephemeral)
```

### Steps to reproduce

Run Pulumi up via Pulumi automation. Not sure what is causing it to happen.

### Expected Behavior

That the command didn't fail.

### Actual Behavior

It failed (see above error).

### Versions used

```
CLI          
Version      3.32.1
Go Version   go1.18.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.4.0
dotnet  unknown
tls     4.4.0

Host     
OS       darwin
Version  12.3.1
Arch     arm64

This project is written in dotnet (/usr/local/share/dotnet/dotnet v6.0.200)

Backend        
URL            file://~
Organizations  

NAME             VERSION
Newtonsoft.Json  13.0.1
Pulumi           3.32.1
Pulumi.Aws       5.4.0
Pulumi.Tls       4.4.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by bjcordery** [comment]
I traced a matching failure through the our deployment pipeline this repo (`pulumi/pulumi-dotnet`) backs, and it points to a specific root cause worth sharing here.

**Symptom** (Pulumi 3.107.3, plain `pulumi up`, not Automation API): a stack with one long-running resource (`aws.elasticache.ReplicationGroup`, ~200s create) succeeds — the CLI prints `+ ... created (202s)` — but ~2s later the update fails:

```
pulumi:pulumi:Stack ... creating (204s) Error occurred trying to send logging message to engine:
Pulumi.LogException: Error occurred during logging: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.OperationCanceledException: The operation was canceled.")
   at async Task Pulumi.Deployment+EngineLogger.LogAsync(...)  ---> Grpc.Core.RpcException: Status(StatusCode="Unavailable", ...)
```

The resource itself is fine — only the log/status channel back to the engine is dead. Same `EngineLogger.LogAsync` / `RpcException: Unavailable` signature as this issue.

**Root cause**: `GrpcEngine.cs` and `GrpcMonitor.cs` both build their channel via `GrpcChannel.ForAddress(...)` with no `HttpHandler` supplied, so it falls back to a default `SocketsHttpHandler`, whose `KeepAlivePingDelay` defaults to `Timeout.InfiniteTimeSpan` — no HTTP/2 keepalive PINGs are ever sent (a known general `grpc-dotnet` footgun: grpc/grpc-dotnet#770). During a multi-minute wait on a slow cloud resource, the SDK makes zero gRPC calls in either direction; something on the network path (NAT/conntrack idle eviction, LB idle timeout, etc.) tears down the idle connection, and the next call — the completion/log message — hits a dead subchannel.

We also confirmed a fire-and-forget detail that matters for anyone considering a try/catch workaround: `Log.Info(...)` starts `Task.Run(() => LogAsync(...))` and hands it to the SDK's internal `Runner._inFlightTasks`, awaited separately by `Runner.WhileRunningAsync`. A fault there fails the whole update regardless of any try/catch at the call site, since `Deployment.InternalInstance` is internal and unreachable from user code — so this can't be worked around from outside the SDK at all.

**Suggested fix** — supply an explicit `HttpHandler` with keepalive enabled in both `GrpcEngine.cs` and `GrpcMonitor.cs`:

```csharp
var channel = GrpcChannel.ForAddress(
    new Uri($"http://{engineAddress}"),
    new GrpcChannelOptions
    {
        MaxReceiveMessageSize = maxRpcMessageSize,
        MaxSendMessageSize = maxRpcMessageSize,
        Credentials = Grpc.Core.ChannelCredentials.Insecure,
        HttpHandler = new SocketsHttpHandler
        {
            PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan,
            KeepAlivePingDelay = TimeSpan.FromSeconds(30),
            KeepAlivePingTimeout = TimeSpan.FromSeconds(30),
            KeepAlivePingPolicy = HttpKeepAlivePingPolicy.WithActiveRequests,
        },
    });
```

Happy to open a PR with this change against both files if that's useful — let me know.

**Comment by Frassle** [comment]
> Happy to open a PR with this change against both files if that's useful — let me know.

Sounds good, go for it :)
