### ISSUE TITLE
Automation API sometimes has a JSON exception and crashes the process

### ISSUE THREAD

**Issue by JoeStead** [pulumi/pulumi-dotnet#166]
### What happened?

When running a deploy, or preview using the Automation API, there seems to be a transient fault that crashes the process.

This is _after_ the preview/up command has completed, so the change is successfully applied but crashes after completion. A re-run tends to fix it.

```
Unhandled exception. System.Text.Json.JsonException: Expected end of string, but instead reached end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 1252.
 ---> System.Text.Json.JsonReaderException: Expected end of string, but instead reached end of data. LineNumber: 0 | BytePositionInLine: 1252.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Utf8JsonReader.TrySkip()
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Utf8JsonReader& reader, JsonSerializerOptions options)
   at Pulumi.Automation.Serialization.Json.MapToModelJsonConverter`2.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Pulumi.Automation.Events.EventLogWatcher.ReadEventsOnce()
   at Pulumi.Automation.Events.EventLogWatcher.ReadEventsOnce()
   at Pulumi.Automation.Events.EventLogWatcher.PollForEvents(CancellationToken externalCancellationToken)
   at Pulumi.Automation.Events.EventLogWatcher.AwaitPollingTask()
   at Pulumi.Automation.Events.EventLogWatcher.Stop()
   at Pulumi.Automation.Commands.LocalPulumiCmd.RunAsync(IList`1 args, String workingDir, IDictionary`2 additionalEnv, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.Workspace.RunStackCommandAsync(String stackName, IList`1 args, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.RunCommandAsync(IList`1 args, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.PreviewAsync(PreviewOptions options, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.PreviewAsync(PreviewOptions options, CancellationToken cancellationToken)
```

### Expected Behavior

For the application to not sporadically crash.

### Steps to reproduce

1. Setup a pulumi project using the automation API
2. Have a stack that does _something_ with AWS (we've seen this on different projects doing different things)
3. Run the program to preview/deploy the stack, and it will sporadically fail.

### Output of `pulumi about`

n/a

Pulumi.automation.api package version => 3.54.1.0

### Additional context

This used to happen very rarely, and now happens in one every three builds or so.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by JoeStead** [comment]
It looks like this line needs to be more defensive: https://github.com/pulumi/pulumi-dotnet/blob/main/sdk/Pulumi.Automation/Events/EventLogWatcher.cs#L104

**Comment by JoeStead** [comment]
This is happening multiple times a day and is beginning to have an affect on our billed GitHub actions usage - can I offer more information to try and resolve this?

**Comment by Zaid-Ajaj** [comment]
Hello @JoeStead thanks a lot for reporting the issue and for the submitting a PR to fix it 🙏 we really appreciate it! Indeed we shouldn't be failing when an engine event can't be parsed.
