### ISSUE TITLE
ImportAsync requires dotnet build to run

### ISSUE THREAD

**Issue by JasonWhall** [pulumi/pulumi-dotnet#323]
### What happened?

When using the `WorkspaceStack.ImportAsync` Method, it currently requires building a .NET project which may not be available if the running program is an executable. The following error message is returned:

<details> 
<summary>Error Message</summary>

```
Importing (SecondStack):
    pulumi:pulumi:Stack MyProject-SecondStack  running 'dotnet build -nologo .'
    pulumi:pulumi:Stack MyProject-SecondStack  MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
    pulumi:pulumi:Stack MyProject-SecondStack  MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
    pulumi:pulumi:Stack MyProject-SecondStack  1 message
Diagnostics:
  pulumi:pulumi:Stack (MyProject-SecondStack):
    MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

error: failed to discover plugin requirements: 'dotnet build -nologo .' exited with non-zero exit code: 1
Unhandled exception. Pulumi.Automation.Commands.Exceptions.CommandException: code: -1
stdout: Importing (SecondStack):
    pulumi:pulumi:Stack MyProject-SecondStack  running 'dotnet build -nologo .'
    pulumi:pulumi:Stack MyProject-SecondStack  MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
    pulumi:pulumi:Stack MyProject-SecondStack  MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
    pulumi:pulumi:Stack MyProject-SecondStack  1 message
Diagnostics:
  pulumi:pulumi:Stack (MyProject-SecondStack):
    MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.


stderr: error: failed to discover plugin requirements: 'dotnet build -nologo .' exited with non-zero exit code: 1


   at Pulumi.Automation.Commands.LocalPulumiCommand.RunAsyncInner(IList`1 args, String workingDir, IDictionary`2 additionalEnv, Action`1 onStandardOutput, Action`1 onStandardError, EventLogFile eventLogFile, CancellationToken cancellationToken)
   at Pulumi.Automation.Commands.LocalPulumiCommand.RunAsync(IList`1 args, String workingDir, IDictionary`2 additionalEnv, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.Workspace.RunStackCommandAsync(String stackName, IList`1 args, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.RunCommandAsync(IList`1 args, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)

```
</details>

The expectation is that it should not need to build the .NET project if it is being executed through the automation API. Speculation from the error message suggests that to import it needs to discover the plugins to use which is obtained by building the project.

### Example

Example to re-produce published here - https://github.com/JasonWhall/pulumi-import-bug-sample

### Output of `pulumi about`

CLI
Version      3.129.0
Go Version   go1.22.6
Go Compiler  gc

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19045 Build 19045
Arch     x86_64

Backend
Name           
URL            file://~
User           
Organizations
Token type     personal

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for the repro.

**Comment by JasonWhall** [comment]
I've self-volunteered to take a look at this, but might need a bit of guidance @justinvp. I believe I've narrowed it down to being 2 issues:

1. The Import operation triggers a call to GetRequiredPackages from the dotnet language host. This method currently is the thing calling `dotnet build` causing the error to occur. There is no conditional behaviour here for dotnet programs so `dotnet build` will always run if `pulumi import` is called.
2. It looks like for refresh (and some other operations) a flag is passed to pulumi called `--exec-kind` which tells pulumi that it is an inline automation api program and then the refresh command skips over the call to trigger GetRequiredPackages. This is currently missing from import command in pulumi/pulumi and also not being set in the `WorkspaceStack.ImportAsync` method in pulumi/pulumi-dotnet

I have a draft proposal to apply the same logic to the update operation here to fix this for import - https://github.com/pulumi/pulumi/compare/master...JasonWhall:pulumi:feature/support-inline-import-dotnet?expand=1 This would allow the following command to run without needing to do `dotnet build`

```
pulumi import --file import.json --exec-kind auto.inline --protect=false --generate-code=false --debug --logtostderr
```

Am I on the right track here or are there other considerations to be made?

**Comment by JasonWhall** [comment]
Thanks @Frassle - That sounds like a lot more of a reasonable approach to me. Will the linked issue to revert the current special case also implement the warn but continue behaviour you've described?

FYI - this bug is a last piece of the puzzle to allow me to programatically "gracefully move" resources between stacks so I'm happy to help contribute if there is an order of changes that need to be made first.

**Comment by Frassle** [comment]
> Will the linked issue to revert the current special case also implement the warn but continue behaviour you've described?

Yes.

> so I'm happy to help contribute if there is an order of changes that need to be made first.

I think its probably just reverting the execkind checks and adding the warnings when gatherPackagesFromProgram/GetRequiredPackages does fail.
