### ISSUE TITLE
Using latest YamlDotNet causes TypeLoadException

### ISSUE THREAD

**Issue by jirikopecky** [pulumi/pulumi-dotnet#353]
### What happened?

I have project that uses `Pulumi.Automation`. When I've added latest `YamlDotNet` NuGet package to generate some config file the `Pulumi.Automation` code started throwing `System.TypeLoadException`. I need to use naming conventions available in recent `YamlDotNet`.

### Example

```
System.TypeLoadException: Method 'ReadYaml' in type 'Pulumi.Automation.Serialization.Yaml.ProjectRuntimeYamlConverter' from assembly 'Pulumi.Automation, Version=3.66.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
      at Pulumi.Automation.Serialization.LocalSerializer.BuildYamlDeserializer()
      at Pulumi.Automation.Serialization.LocalSerializer..ctor()
      at Pulumi.Automation.LocalWorkspace..ctor(PulumiCommand cmd, LocalWorkspaceOptions options, CancellationToken cancellationToken)
      at Pulumi.Automation.LocalWorkspace.CreateStackHelperAsync(InlineProgramArgs args, Func`4 initFunc, CancellationToken cancellationToken)
...
```

### Output of `pulumi about`

```
CLI
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.60.0
resource  cloudflare    5.37.1
language  dotnet        unknown
resource  random        4.16.4
resource  tls           5.0.5

Host
OS       darwin
Version  15.0
Arch     arm64

This project is written in dotnet: executable='/opt/homebrew/bin/dotnet' version='8.0.402'

Backend
Name           pulumi.com
URL            ***
User           ***
Organizations  ***
Token type     personal

Dependencies:
NAME                                                  VERSION
FluentValidation                                      11.9.2
JetBrains.Annotations                                 2024.2.0
Pulumi                                                3.66.2
Pulumi.AzureNative                                    2.60.0
Pulumi.Cloudflare                                     5.37.1
Pulumi.Random                                         4.16.4
Pulumi.Tls                                            5.0.5
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by realrubberduckdev** [comment]
Hi @jirikopecky 

Any idea when will this be shipped?

We are hitting this issue in a project as we want to use `Yamldotnet 16.2.0` with `Pulumi.Automation 3.67.1`.

For now, I will pin `Yamldotnet` to `15.3.0` as a workaround.

**Comment by jirikopecky** [comment]
Hi @realrubberduckdev, I'm not affiliated with Pulumi 🙂 Maybe @justinvp can help answer this question.
