### ISSUE TITLE
Serialization failure exporting an `[OutputType]` class as a stack export in .NET

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-dotnet#58]
I get this:

```
 System.InvalidOperationException: Pulumi.Kubernetes.Types.Outputs.Rbac.V1.Subject is not a supported argument type.
        monitor.registerResourceOutputs(...).subjects.id[0]
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Serialization.Serializer.SerializeListAsync(String ctx, IList list)
```

When trying to return to add the last line (`subjects`) below:

```cs
             return new Dictionary<string, object>{
                { "namespacePhase", ns.Status.Apply(status => status.Phase) },
                { "revisionData", revision.Data },
                { "subjects", binding.Subjects },
            };
```

The type of that property is:

```cs
Output<System.Collections.Immutable.ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Rbac.V1.Subject>> RoleBinding.Subjects
```

It appears that the serialization we do for `registerResourceOutputs` and/or stack exports is not correctly supporting `OutputType` classes.

**Comment by Badabum** [comment]
Just want to bump attention here as it seem that issue got forgotten. Any plans to support this or related use cases like anonymous types serialization?
